[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
dotenvy = "0.15.7"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.1"
sdl2 = { version = "0.37.0", features = ["bundled"] }
